# Generated by Django 2.2 on 2021-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='ip',
            field=models.TextField(default=''),
        ),
    ]
