# Generated by Django 2.2 on 2021-09-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210901_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='ip',
        ),
    ]
